
server:
  port: ${PORT:9023}


eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://172.17.0.3:8761}/eureka/
       
server:
  port: ${PORT:9023}
