
server:
  port: ${PORT:9023}


eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/

---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://172.17.0.2:8888  
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://172.18.0.2:8761}/eureka/
          
server:
  port: ${PORT:9023}
